services:
  # O serviço da aplicação Node.js continua o mesmo
  pdf-tools:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    shm_size: '2gb'
    environment:
      # Podemos definir como 'development' para o ambiente local
      - NODE_ENV=development
    restart: always

  # Serviço do Nginx para o ambiente local
  nginx:
    image: nginx:stable-alpine
    ports:
      # Mapeia a porta 81 do seu computador para a porta 81 do contêiner Nginx
      - "81:81"
    volumes:
      # Monta o NOVO arquivo de configuração local
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pdf-tools
    restart: always