services:
  # O serviço da aplicação Node.js
  pdf-tools:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - pdf_uploads:/app/uploads  # <-- Alteração para usar o volume nomeado
    shm_size: '2gb'
    environment:
      - NODE_ENV=development
    restart: always

  # Serviço do Nginx para o ambiente local
  nginx:
    image: nginx:stable-alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pdf-tools
    restart: always

# Define o volume nomeado que será gerenciado pelo Docker
volumes:
  pdf_uploads: